### ISSUE TITLE
3. As a player, I want a more colorful paddles.

### ISSUE THREAD

**Issue by mjgjtie** [mjgjtie/PongGame#10]
Thiết kế ý tưởng : 10'
Tìm hình thay thế Paddles : 5'
Đưa hình ảnh tìm được vào eclip : 60'
Testing : 10'
Sửa lỗi : 5'
Tổng : 1h30'

**Comment by miscoarh** [comment]
Thiết kế ý tưởng : 10'

**Comment by miscoarh** [comment]
Tìm hình thay thế Padddles : 2'

**Comment by miscoarh** [comment]
Đưa hình ảnh vào trong Eclipse : 35'

**Comment by miscoarh** [comment]
Testing : 2'

**Comment by miscoarh** [comment]
Sửa lỗi : 0'

**Comment by miscoarh** [comment]
Tổng : 49'
